config/routes.rb
Rails.application.routes.draw do
  root 'exchanges#index'
  get 'convert', to: 'exchanges#convert'
  get 'convertcrypto', to: 'exchanges#convertcrypto'
  get 'crypto_box', to: 'exchanges#crypto_box'
  get 'coin_box', to: 'exchanges#coin_box'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def index
  end

  def convert
    value = ExchangeService.new(params[:source_currency], params[:target_currency], params[:amount]).perform
    render json: {"value": value}
  end

  def convertcrypto
    value = CryptoService.new(params[:source_crypto], params[:target_crypto], params[:amount]).perform
    render json: {"value": value}
  end

  def crypto_box
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def coin_box
    respond_to do |format|
      format.html {}
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
 
  def currency_list
    [
      'AUD', 'BGN', 'BRL', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP',
      'HKD', 'HRK', 'HUF', 'IDR', 'ILS', 'INR', 'JPY', 'KRW', 'MXN',
      'MYR', 'NOK', 'NZD', 'PHP', 'PLN', 'RON', 'RUB', 'SEK', 'SGD',
      'THB', 'TRY', 'USD', 'ZAR', 'BTC', 'ETH', 'XRP', 'BCH', 'EOS', 
      'TRX', 'NEO', 'BCD', 'XMR', 'DASH', 'USDT', 'XEM', 'VEN', 'BNB',
      'ETC', 'QTUM', 'OMG', 'BCN', 'ICX', 'ZEC', 'LSK', 'SPRTS', 'AE',
      'DCR', 'BTG', 'ZRX', 'SC', 'NET', 'STEEM', 'XVG', 'BTS', 'WAN', 
      'WAVES', 'GNT', 'REP', 'STRAT', 'SBD', 'DOGE','PPT', 'DGB', 'BTCP', 
      'WTC', 'IOST', 'SNT', 'DGD', 'HSR', 'NAS', 'AION', 'LRC', 'BAT', 'KMD', 
      'BLZ', 'ARK', 'ELF', 'GXS', 'ARDR', 'BNT', 'UBTC', 'MAID', 'DCN', 'PIVX',
      'MONA', 'RDD', 'GAS', 'SKY', 'BQX', 'SYS', 'POLY', 'QASH', 'FUN', 'VERI',
      'MITH', 'ETN', 'ENG', 'SUB', 'B2G', 'XZC', 'NXT', 'KIN', 'DROP', 'FCT',
      'SOC', 'POWR', 'NXS', 'BLOCK', 'GTO', 'MANA', 'WAX', 'MYB', 'EMC', 'RLC',
      'LINK', 'SALT', 'GBYTE', 'MCO', 'LTC', 'ADA', 'XLM', 'ALP', 'IOTA',
    ]
  end

  def crypto_list
    [
      'BTC', 'ETH', 'XRP', 'BCH', 'EOS', 'LTC', 'ADA', 'XLM', 'ALP', 'IOTA',
      'TRX', 'NEO', 'BCD', 'XMR', 'DASH', 'USDT', 'XEM', 'VEN', 'BNB',
      'ETC', 'QTUM', 'OMG', 'BCN', 'ICX', 'ZEC', 'LSK', 'SPRTS', 'AE',
      'DCR', 'BTG', 'ZRX', 'SC', 'NET', 'STEEM', 'XVG', 'BTS', 'WAN', 
      'WAVES', 'GNT', 'REP', 'STRAT', 'SBD', 'DOGE','PPT', 'DGB', 'BTCP', 
      'WTC', 'IOST', 'SNT', 'DGD', 'HSR', 'NAS', 'AION', 'LRC', 'BAT', 'KMD', 
      'BLZ', 'ARK', 'ELF', 'GXS', 'ARDR', 'BNT', 'UBTC', 'MAID', 'DCN', 'PIVX',
      'MONA', 'RDD', 'GAS', 'SKY', 'BQX', 'SYS', 'POLY', 'QASH', 'FUN', 'VERI',
      'MITH', 'ETN', 'ENG', 'SUB', 'B2G', 'XZC', 'NXT', 'KIN', 'DROP', 'FCT',
      'SOC', 'POWR', 'NXS', 'BLOCK', 'GTO', 'MANA', 'WAX', 'MYB', 'EMC', 'RLC',
      'LINK', 'SALT', 'GBYTE', 'MCO'
    ]
  end
end

app/views/exchanges/_coin_box.html.erb
<div class="text-center div-btn mb-0 mt-4 mb-2">
  <span>MODE:</span>
  <button class="btn-moeda coin shadow-sm" id='crypto' >
    <%= link_to "COIN", crypto_box_path, remote: true %>
  </button>
</div>

<%= form_tag('/convert', method: :get, id: 'exchange_form') do %>
            
  <%# MOEDA LOCAL %>
  <div class="form-group moeda mt-1">
    <label for="exampleFormControlSelect1">Local Currency</label>
    <%= select_tag 'source_currency', options_for_select(currency_list, disabled: crypto_list, selected: 'USD'), class: 'form-control shadow form-control-lg dropdown', id: 'source_currency' %>
  </div>

  <%# BOTÃO TROCA %>
  <div class="text-center div-btn mt-3 mb-1">
    <button class="btn-troca shadow-sm" id='troca' >
      <i class="fas fa-sync fa-xs"></i>
    </button>
  </div>

  <%# MOEDA DESEJADA %>
  <div class="form-group moeda mt-0">
    <label for="exampleFormControlSelect1">Desired Currency</label>
    <%= select_tag 'target_currency', options_for_select(currency_list, disabled: crypto_list, selected: 'BRL'), class: 'form-control shadow form-control-lg dropdown', id: 'target_currency'%>
  </div>

  <%# LINHA HR %>
  <div class="text-center mt-3 div-linha">
    <hr class="linha shadow">
  </div>

  <%# QUANTIDADE %>
  <div class="form-group moeda mb-2">
    <input type='number' name='amount' id='amount' class='form-control shadow quantidade form-control-lg' placeholder='Amount ($)' step='any' required>
  </div>

  <%# BOTAO CONVERTER %>
  <%# <div class="text-center mt-3 mb-3">
    <button type="submit" class="btn botao shadow">EXCHANGE</button>
  </div> %>

  <%# RESULTADO %>
  <div class="form-group moeda mt-2 mb-2">
    <input type='text' id='result' name='result' class='form-control shadow resultado form-control-lg dropdown' placeholder='RESULT' readonly>
  </div>

<% end %> <%# -------- Fim%>

app/views/exchanges/_crypto_box.html.erb
<div class="text-center div-btn mb-0 mt-4 mb-2">
  <span>MODE:</span>
    <button class="btn-moeda crypto shadow-sm" id='crypto' >
      <%= link_to "CRYPTO", coin_box_path, remote: true %>
    </button>
</div>

<%= form_tag('/convertcrypto', method: :get, id: 'crypto_form') do %>
            
  <%# MOEDA LOCAL %>
  <div class="form-group moeda mt-1">
    <label for="exampleFormControlSelect1">Local Currency</label>
    <%= select_tag 'source_currency', options_for_select(currency_list, 'BTC'), class: 'form-control shadow form-control-lg dropdown', id: 'source_currency' %>
  </div>

  <%# BOTÃO TROCA %>
  <div class="text-center div-btn mb-0 mt-3 mb-1">
    <button class="btn-troca shadow-sm" id='troca' >
      <i class="fas fa-sync fa-xs"></i>
    </button>
  </div>

  <%# MOEDA DESEJADA %>
  <div class="form-group moeda mt-0">
    <label for="exampleFormControlSelect1">Desired Currency</label>
    <%= select_tag 'target_currency', options_for_select(currency_list, 'USD'), class: 'form-control shadow form-control-lg dropdown', id: 'target_currency'%>
  </div>

  <%# LINHA HR %>
  <div class="text-center mt-3 div-linha">
    <hr class="linha shadow">
  </div>

  <%# QUANTIDADE %>
  <div class="form-group moeda mb-2">
    <input type='number' name='amount' id='amount' class='form-control shadow quantidade form-control-lg' placeholder='Amount ($)' step='any' required>
  </div>

  <%# BOTAO CONVERTER %>
  <%# <div class="text-center mt-3 mb-3">
    <button type="submit" class="btn botao shadow">EXCHANGE</button>
  </div> %>

  <%# RESULTADO %>
  <div class="form-group moeda mt-2 mb-2">
    <input type='text' id='result' name='result' class='form-control shadow resultado form-control-lg dropdown' placeholder='RESULT' readonly>
  </div>

<% end %> <%# -------- Fim%>

app/views/exchanges/_exchange_box.html.erb
<div class="d-flex flex-wrap justify-content-center align-items-center">
        <div class="card text-white mb-3 shadow-sm" id="card">

          <%= render 'coin_box' %>      

        </div>
        <div class="text-center"><span class="s1 font-weight-bold">ONEBIT</span><span class="s2 font-weight-bold">EXCHANGE</span><span class="s3 font-weight-bold">V2</span></div>
        
      </div>

app/views/exchanges/coin_box.js.erb
$("#card").html("<%= escape_javascript(render :partial => 'coin_box') %>");


$("#troca").click(function (e) {
  e.preventDefault();

  const elem1 = $('#source_currency').val();
  const elem2 = $('#target_currency').val();
  const selectedOption1 = elem1;

  document.getElementById('source_currency').value = elem2;
  document.getElementById('target_currency').value = selectedOption1;

  
});

(function() {
  $(document).ready(function() {
    return $('#amount').on('keypress', function(e) {
      if (e.which === 13) {
        e.preventDefault();
        if ($('#exchange_form').attr('action') === '/convert') {
          $.ajax('/convert', {
            type: 'GET',
            dataType: 'json',
            data: {
              source_currency: $("#source_currency").val(),
              target_currency: $("#target_currency").val(),
              amount: $("#amount").val()
            },
            error: function(jqXHR, textStatus, errorThrown) {
              return alert(errorThrown);
            },
            success: function(data, text, jqXHR) {
              return $('#result').val(data.value.toFixed(2));
            }
          });
          return false;
        }
      }
    });
  });

}).call(this);

app/views/exchanges/crypto_box.js.erb
$("#card").html("<%= escape_javascript(render :partial => 'crypto_box') %>");

$("#troca").click(function (e) {
  e.preventDefault();

  const elem1 = $('#source_currency').val();
  const elem2 = $('#target_currency').val();
  const selectedOption1 = elem1;

  document.getElementById('source_currency').value = elem2;
  document.getElementById('target_currency').value = selectedOption1;

  
});

(function() {
  $(document).ready(function() {
    return $('#amount').on('keypress', function(e) {
      if (e.which === 13) {
        e.preventDefault();
        if ($('#crypto_form').attr('action') === '/convertcrypto') {
          $.ajax('/convertcrypto', {
            type: 'GET',
            dataType: 'json',
            data: {
              source_crypto: $("#source_currency").val(),
              target_crypto: $("#target_currency").val(),
              amount: $("#amount").val()
            },
            error: function(jqXHR, textStatus, errorThrown) {
              return alert(errorThrown);
            },
            success: function(data, text, jqXHR) {
              return $('#result').val(data.value);
            }
          });
          return false;
        }
      }
    });
  });

}).call(this);

app/views/exchanges/index.html.erb
<body>
  <div class="container h-100 p-0 div-pai">
    
    <div class="row h-100 justify-content-center align-items-center">
      <%= render 'exchange_box' %>
    </div>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneBitExchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>